# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - payflowx-api-qalb

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore API dependencies
        run: dotnet restore PayFlowX/PayFlowX.csproj

      - name: Build API
        run: dotnet build PayFlowX/PayFlowX.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test PayFlowX.Tests/PayFlowX.Tests.csproj --configuration Release

      - name: Publish API
        run: dotnet publish PayFlowX/PayFlowX.csproj -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_330852BA7DF9471EBD7BCE68F51264F3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_47522DFDB5084F4FBAAAB94D0142554B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D3FD8ED6680E43348A1C6D344EC39911 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'payflowx-api-qalb'
          slot-name: 'Production'
          package: ./publish